# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20170504_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='food',
            field=models.ManyToManyField(related_name='user_food', to='diary.Food'),
        ),
    ]
