# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20170505_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default=None, upload_to=None),
        ),
    ]
