# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank='true', upload_to='profile_image'),
        ),
    ]
