# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_auto_20170603_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(upload_to='images'),
        ),
    ]
