# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20170714_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(default='/images/bri.jpg', upload_to='diary/images'),
        ),
    ]
