# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='type_of',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
