# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_auto_20170714_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meal',
            field=models.ManyToManyField(related_name='user_meal', to='diary.Meal'),
        ),
    ]
